# Generated by Django 3.1.6 on 2021-02-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Influencers',
            new_name='Influencer',
        ),
    ]
