# Generated by Django 3.1.6 on 2021-02-22 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_database', '0002_auto_20210219_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 2, 22, 14, 46, 18, 947596, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influencer',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=datetime.datetime(2021, 2, 22, 14, 46, 25, 703628, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=200)),
                ('video_url', models.CharField(max_length=200)),
                ('video_views', models.IntegerField()),
                ('video_comments', models.IntegerField()),
                ('video_likes', models.IntegerField()),
                ('video_dislikes', models.IntegerField()),
                ('channel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_database.influencer')),
            ],
        ),
    ]
