# Generated by Django 3.1.6 on 2021-02-22 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_database', '0003_auto_20210222_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date_of_publication',
            field=models.DateField(default=datetime.datetime(2021, 2, 22, 20, 32, 24, 515471, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='influencer',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='When created'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='When updated'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
