# Generated by Django 3.1.6 on 2021-02-24 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_database', '0004_auto_20210222_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='video_comments',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_dislikes',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_likes',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_views',
        ),
        migrations.AddField(
            model_name='content',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 2, 24, 9, 15, 4, 278647, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_update', models.DateField(auto_now=True)),
                ('video_views', models.IntegerField()),
                ('video_comments', models.IntegerField()),
                ('video_likes', models.IntegerField()),
                ('video_dislikes', models.IntegerField()),
                ('video_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_database.content')),
            ],
            options={
                'ordering': ['-video_url__date_of_publication', '-video_views'],
            },
        ),
    ]
